services:
  - type: web
    name: poc-finance
    runtime: docker
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
    healthCheckPath: /login
